/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainbattleScreen;

/**
 *
 * @author Acer
 */
public class BattleScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BattleScreen.class.getName());

    /**
     * Creates new form BattleScreen
     */
    public BattleScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ManaBarHydra = new javax.swing.JProgressBar();
        HPBarStudents = new javax.swing.JProgressBar();
        HPBarHydra = new javax.swing.JProgressBar();
        ManaBarStudents = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatBox = new javax.swing.JTextArea();
        turnIndicator = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        MoraleMeter = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\OneDrive\\Pictures\\Screenshots\\Hydraf.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 380, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\OneDrive\\Pictures\\Screenshots\\Ethan.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 70, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\OneDrive\\Pictures\\Screenshots\\Shawn.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 80, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\OneDrive\\Pictures\\Screenshots\\Dwight.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, 60));

        ManaBarHydra.setValue(100);
        ManaBarHydra.setStringPainted(true);
        getContentPane().add(ManaBarHydra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 180, 20));

        HPBarStudents.setBackground(new java.awt.Color(255, 255, 255));
        HPBarStudents.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        HPBarStudents.setForeground(new java.awt.Color(51, 255, 51));
        HPBarStudents.setValue(100);
        HPBarStudents.setStringPainted(true);
        HPBarStudents.setUI(new javax.swing.plaf.basic.BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(java.awt.Graphics g, javax.swing.JComponent c) {
                if (!(g instanceof java.awt.Graphics2D)) {
                    return;
                }
                // This forces the bar to fill with your chosen foreground color 
                // instead of the Nimbus orange gradient
                c.setForeground(new java.awt.Color(46, 204, 113)); // Example: Nice Green
                super.paintDeterminate(g, c);
            }
        });
        getContentPane().add(HPBarStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 180, 20));

        HPBarHydra.setForeground(new java.awt.Color(51, 255, 51));
        HPBarHydra.setValue(100);
        HPBarHydra.setStringPainted(true);
        getContentPane().add(HPBarHydra, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 200, 20));

        ManaBarStudents.setValue(100);
        ManaBarStudents.setStringPainted(true);
        getContentPane().add(ManaBarStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, 20));

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 0));

        ChatBox.setColumns(20);
        ChatBox.setLineWrap(true);
        ChatBox.setRows(5);
        jScrollPane1.setViewportView(ChatBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 240, 110));

        turnIndicator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        turnIndicator.setForeground(new java.awt.Color(255, 51, 51));
        turnIndicator.setText("Shawn's Turn");
        getContentPane().add(turnIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 80, -1));
        turnIndicator.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 800, 240));

        MoraleMeter.setForeground(new java.awt.Color(255, 153, 0));
        MoraleMeter.setValue(50);
        MoraleMeter.setStringPainted(true);
        getContentPane().add(MoraleMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 170, 20));

        jButton1.setText("Potions:");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 70, 30));

        BackGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\OneDrive\\Pictures\\Screenshots\\Room.png")); // NOI18N
        BackGround.setText("jLabel5");
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 360));

        jButton2.setText("Skill1");

        jButton3.setText("Skill2");

        jButton4.setText("Skill3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 290, -1));

        jButton5.setText("Attack");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 100, 30));

        jButton6.setText("Defend");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 100, 30));

        jButton7.setText("Skills1");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 90, 50));

        jButton8.setText("Skills2");
        jButton8.setToolTipText("");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 100, 50));

        jButton9.setText("Skills3");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 90, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BattleScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JTextArea ChatBox;
    private javax.swing.JProgressBar HPBarHydra;
    private javax.swing.JProgressBar HPBarStudents;
    private javax.swing.JProgressBar ManaBarHydra;
    private javax.swing.JProgressBar ManaBarStudents;
    private javax.swing.JProgressBar MoraleMeter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel turnIndicator;
    // End of variables declaration//GEN-END:variables
}
