/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game_UI;
import java.util.ArrayList;
import GameEngine.IBattleScreenUI;
import Characters.*;
import GameEngine.*;
/**
 *
 * @author Acer
 */
public class BattleScreen extends javax.swing.JFrame implements IBattleScreenUI {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BattleScreen.class.getName());
    private ArrayList<GameCharacter> party;
    private BattleController controller;
    private int currentActorIndex = 0; 

    private final String[] TURN_ORDER = {"Front", "Above", "Below"};
    /**
     * Creates new form BattleScreen
     */
public BattleScreen(ArrayList<GameCharacter> party) {
        initComponents();
    this.party = party;
    this.controller = new BattleController(this);
    HPBarStudents.setStringPainted(true);
    ManaBarStudents.setStringPainted(true);
    MoraleMeter.setStringPainted(true);
    MoraleMeter.setValue(100);
    setupPartyImages();
    controller.getEngine().initializeParty(party);  // ← set party first
    controller.spawnNextBoss();
    controller.appendChatMessage("Battle started!");
    refreshActorDisplay();
    }
public BattleScreen() {
    initComponents();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlblBoss = new javax.swing.JLabel();
        jlblTop = new javax.swing.JLabel();
        jlblFront = new javax.swing.JLabel();
        jlblBottom = new javax.swing.JLabel();
        ManaBarHydra = new javax.swing.JProgressBar();
        HPBarStudents = new javax.swing.JProgressBar();
        HPBarHydra = new javax.swing.JProgressBar();
        ManaBarStudents = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatBox = new javax.swing.JTextArea();
        turnIndicator = new javax.swing.JLabel();
        MoraleMeter = new javax.swing.JProgressBar();
        BackGround = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnAllySkill1 = new javax.swing.JButton();
        jbtnAllySkill2 = new javax.swing.JButton();
        jbtnAllySkill3 = new javax.swing.JButton();
        jbtnAttack = new javax.swing.JButton();
        jbtnDefend = new javax.swing.JButton();
        jbtnBossSkill1 = new javax.swing.JButton();
        jbtnBossSkill2 = new javax.swing.JButton();
        jbtnBossSkill3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbtnPotionRevive = new javax.swing.JButton();
        jbtnPotionHp = new javax.swing.JButton();
        JbtnPotionMana = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jprogBarRage = new javax.swing.JProgressBar();
        Backgroundright = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bro.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblBoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Hydra1.png"))); // NOI18N
        jlblBoss.setText("jLabel1");
        getContentPane().add(jlblBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 360, 240));

        jlblTop.setText("jLabel2");
        getContentPane().add(jlblTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 70, 60));

        jlblFront.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Shawn.png"))); // NOI18N
        jlblFront.setText("jLabel3");
        getContentPane().add(jlblFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, 70));

        jlblBottom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Dwight.png"))); // NOI18N
        jlblBottom.setText("jLabel4");
        getContentPane().add(jlblBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, 60));

        ManaBarHydra.setValue(100);
        ManaBarHydra.setStringPainted(true);
        getContentPane().add(ManaBarHydra, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 330, 20));

        HPBarStudents.setBackground(new java.awt.Color(255, 255, 255));
        HPBarStudents.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        HPBarStudents.setForeground(new java.awt.Color(51, 255, 51));
        HPBarStudents.setValue(100);
        HPBarStudents.setStringPainted(true);
        HPBarStudents.setUI(new javax.swing.plaf.basic.BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(java.awt.Graphics g, javax.swing.JComponent c) {
                if (!(g instanceof java.awt.Graphics2D)) {
                    return;
                }
                // This forces the bar to fill with your chosen foreground color 
                // instead of the Nimbus orange gradient
                c.setForeground(new java.awt.Color(46, 204, 113)); // Example: Nice Green
                super.paintDeterminate(g, c);
            }
        });
        getContentPane().add(HPBarStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 350, 20));

        HPBarHydra.setForeground(new java.awt.Color(51, 255, 51));
        HPBarHydra.setValue(100);
        HPBarHydra.setStringPainted(true);
        getContentPane().add(HPBarHydra, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 350, 20));

        ManaBarStudents.setBackground(new java.awt.Color(255, 255, 255));
        ManaBarStudents.setValue(100);
        ManaBarStudents.setStringPainted(true);
        getContentPane().add(ManaBarStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 350, 20));

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 0));

        ChatBox.setColumns(20);
        ChatBox.setLineWrap(true);
        ChatBox.setRows(5);
        jScrollPane1.setViewportView(ChatBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 180, 380));

        turnIndicator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        turnIndicator.setForeground(new java.awt.Color(255, 51, 51));
        turnIndicator.setText("Shawn's Turn");
        getContentPane().add(turnIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 80, -1));
        turnIndicator.getAccessibleContext().setAccessibleName("");

        MoraleMeter.setForeground(new java.awt.Color(255, 153, 0));
        MoraleMeter.setValue(50);
        MoraleMeter.setStringPainted(true);
        getContentPane().add(MoraleMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 340, 20));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Roomss.png"))); // NOI18N
        BackGround.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 380));

        jbtnAllySkill1.setText("Skill1");
        jbtnAllySkill1.addActionListener(this::jbtnAllySkill1ActionPerformed);

        jbtnAllySkill2.setText("Skill2");
        jbtnAllySkill2.addActionListener(this::jbtnAllySkill2ActionPerformed);

        jbtnAllySkill3.setText("Skill3");
        jbtnAllySkill3.addActionListener(this::jbtnAllySkill3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnAllySkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAllySkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAllySkill3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAllySkill2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAllySkill3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAllySkill1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 500, 100));

        jbtnAttack.setText("Attack");
        jbtnAttack.addActionListener(this::jbtnAttackActionPerformed);
        getContentPane().add(jbtnAttack, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 100, 30));

        jbtnDefend.setText("Defend");
        jbtnDefend.addActionListener(this::jbtnDefendActionPerformed);
        getContentPane().add(jbtnDefend, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 100, 30));

        jbtnBossSkill1.setText("Skills1");
        jbtnBossSkill1.addActionListener(this::jbtnBossSkill1ActionPerformed);
        getContentPane().add(jbtnBossSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 190, 50));

        jbtnBossSkill2.setText("Skills2");
        jbtnBossSkill2.setToolTipText("");
        jbtnBossSkill2.addActionListener(this::jbtnBossSkill2ActionPerformed);
        getContentPane().add(jbtnBossSkill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 160, 50));

        jbtnBossSkill3.setText("Skills3");
        jbtnBossSkill3.addActionListener(this::jbtnBossSkill3ActionPerformed);
        getContentPane().add(jbtnBossSkill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 490, 170, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 330, -1));

        jbtnPotionRevive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/revive.png"))); // NOI18N
        jbtnPotionRevive.addActionListener(this::jbtnPotionReviveActionPerformed);

        jbtnPotionHp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/health.png"))); // NOI18N
        jbtnPotionHp.addActionListener(this::jbtnPotionHpActionPerformed);

        JbtnPotionMana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mana.png"))); // NOI18N
        JbtnPotionMana.addActionListener(this::JbtnPotionManaActionPerformed);

        jButton1.setText("Potions:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnPotionHp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnPotionMana, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(jbtnPotionRevive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPotionHp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JbtnPotionMana, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnPotionRevive)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 100, 210));

        jprogBarRage.setForeground(new java.awt.Color(255, 0, 0));
        jprogBarRage.setValue(35);
        jprogBarRage.setStringPainted(true);
        getContentPane().add(jprogBarRage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 270, 20));

        Backgroundright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Roomss.png"))); // NOI18N
        Backgroundright.setText("jLabel1");
        Backgroundright.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Backgroundright, new org.netbeans.lib.awtextra.AbsoluteConstraints(1028, 0, 180, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void refreshActorDisplay() {
    GameCharacter actor = getActiveActor();

    // Update skill buttons
    String[] raw = actor.getSkillname();
    jbtnAllySkill1.setText(raw.length > 1 ? raw[1] : "Skill 1");
    jbtnAllySkill2.setText(raw.length > 3 ? raw[3] : "Skill 2");
    jbtnAllySkill3.setText(raw.length > 5 ? raw[5] : "Skill 3");

    // Update turn indicator
    turnIndicator.setText(actor.getName() + "'s Turn");

    // Update the correct label based on the character's position
    String imagePath = getImagePath(actor.getName());
    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
        getClass().getResource(imagePath));

    switch (actor.getPosition().toLowerCase()) {
        case "front" -> jlblFront.setIcon(icon);
        case "above" -> jlblTop.setIcon(icon);
        case "below" -> jlblBottom.setIcon(icon);
    }
}
    private String getImagePath(String characterName) {
    return switch (characterName.toLowerCase()) {
        case "shawn"    -> "/assets/Shawn.png";
        case "ethan"    -> "/assets/Ethan.png";
        case "dwight"   -> "/assets/Dwights.png";
        case "omar"     -> "/assets/Omars.png";
        case "princess" -> "/assets/Camachos.png";
        default         -> "/assets/Shawn.png";
    };
}
    public void updateBossSkillButtons(String[] skillNames) {
    if (skillNames.length > 1) jbtnBossSkill1.setText(skillNames[1]);
    if (skillNames.length > 3) jbtnBossSkill2.setText(skillNames[3]);
    if (skillNames.length > 5) jbtnBossSkill3.setText(skillNames[5]);
}
    @Override
    public void setRageMeter(int percentage) {
     jprogBarRage.setValue(percentage);
    }
        private void setupPartyImages() {
    for (GameCharacter c : party) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
            getClass().getResource(getImagePath(c.getName())));
        switch (c.getPosition().toLowerCase()) {
            case "front" -> jlblFront.setIcon(icon);
            case "above" -> jlblTop.setIcon(icon);
            case "below" -> jlblBottom.setIcon(icon);
        }
    }
}
    private GameCharacter getActiveActor() {
    String currentPos = TURN_ORDER[currentActorIndex];
    for (GameCharacter c : party) {
        if (c.getPosition().equalsIgnoreCase(currentPos) && c.getHp() > 0) {
            return c;
        }
    }
    // If that slot is dead, skip to next alive character
    for (GameCharacter c : party) {
        if (c.getHp() > 0) return c;
    }
    return party.get(0);
    }
    private void advanceTurn() {
    currentActorIndex = (currentActorIndex + 1) % TURN_ORDER.length;
    refreshActorDisplay();  // ← ADD this
    controller.appendChatMessage("--- " + getActiveActor().getName() + "'s turn ---");
}
    private void jbtnBossSkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBossSkill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBossSkill1ActionPerformed

    private void jbtnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAttackActionPerformed
        controller.executePlayerAction(0, getActiveActor());
        advanceTurn();
    }//GEN-LAST:event_jbtnAttackActionPerformed

    
    @Override
    public void setHPBarBoss(int percentage) {
        HPBarHydra.setValue(percentage);
    }

    @Override
    public void setManaBarBoss(int value) {
        ManaBarHydra.setValue(value);
    }

    @Override
    public void setHPBarStudents(int percentage) {
        HPBarStudents.setValue(percentage);
    }
    public void updateMoraleBar(int percentage) {
    MoraleMeter.setValue(percentage);
    }
    @Override
    public void setManaBarStudents(int percentage) {
        ManaBarStudents.setValue(percentage);
    }

    @Override
    public void setTurnIndicator(String text) {
        turnIndicator.setText(text);
    }

    @Override
    public void updateStatusDisplay(String text) {
        // Can display in status label if needed
    }

    @Override
    public void appendToChatBox(String message) {
        ChatBox.append(message);
    }

    @Override
    public void clearChatBox() {
        ChatBox.setText("");
    }

    @Override
public void updateSkillButtons(String[] skillNames) {
    if (skillNames.length > 0) jbtnAllySkill1.setText(skillNames[0]);  // ← fix
    if (skillNames.length > 1) jbtnAllySkill2.setText(skillNames[1]);  // ← fix
    if (skillNames.length > 2) jbtnAllySkill3.setText(skillNames[2]);  // ← fix
}

    @Override
public void setActionButtonsEnabled(boolean enabled) {
    jbtnAttack.setEnabled(enabled);
    jbtnDefend.setEnabled(enabled);
    jbtnAllySkill1.setEnabled(enabled);  // ← fix
    jbtnAllySkill2.setEnabled(enabled);  // ← fix
    jbtnAllySkill3.setEnabled(enabled);  // ← fix
}

    @Override
    public void setBossImage(String imagePath) {
    try {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
            getClass().getResource(imagePath));
        jlblBoss.setIcon(icon);
        jlblBoss.revalidate();
        jlblBoss.repaint();
    } catch (Exception e) {
        logger.log(java.util.logging.Level.WARNING, "Boss image not found: " + imagePath, e);
    }
}
    @Override
    public void setPartyDisplay(String[] studentNames) {
        // Implementation for party display if needed
    }
    private void jbtnPotionReviveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotionReviveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPotionReviveActionPerformed

    private void jbtnPotionHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotionHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPotionHpActionPerformed

    private void JbtnPotionManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPotionManaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnPotionManaActionPerformed

    private void jbtnDefendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDefendActionPerformed
        GameCharacter actor = getActiveActor();
    controller.appendChatMessage(actor.defend());
     advanceTurn();
    }//GEN-LAST:event_jbtnDefendActionPerformed

    private void jbtnAllySkill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAllySkill1ActionPerformed
        controller.executePlayerAction(1, getActiveActor());
         advanceTurn();
    }//GEN-LAST:event_jbtnAllySkill1ActionPerformed

    private void jbtnAllySkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAllySkill2ActionPerformed
        controller.executePlayerAction(2, getActiveActor());
         advanceTurn();
    }//GEN-LAST:event_jbtnAllySkill2ActionPerformed

    private void jbtnAllySkill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAllySkill3ActionPerformed
        controller.executePlayerAction(3, getActiveActor());
         advanceTurn();
    }//GEN-LAST:event_jbtnAllySkill3ActionPerformed

    private void jbtnBossSkill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBossSkill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBossSkill2ActionPerformed

    private void jbtnBossSkill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBossSkill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBossSkill3ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BattleScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel Backgroundright;
    private javax.swing.JTextArea ChatBox;
    private javax.swing.JProgressBar HPBarHydra;
    private javax.swing.JProgressBar HPBarStudents;
    private javax.swing.JButton JbtnPotionMana;
    private javax.swing.JProgressBar ManaBarHydra;
    private javax.swing.JProgressBar ManaBarStudents;
    private javax.swing.JProgressBar MoraleMeter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAllySkill1;
    private javax.swing.JButton jbtnAllySkill2;
    private javax.swing.JButton jbtnAllySkill3;
    private javax.swing.JButton jbtnAttack;
    private javax.swing.JButton jbtnBossSkill1;
    private javax.swing.JButton jbtnBossSkill2;
    private javax.swing.JButton jbtnBossSkill3;
    private javax.swing.JButton jbtnDefend;
    private javax.swing.JButton jbtnPotionHp;
    private javax.swing.JButton jbtnPotionRevive;
    private javax.swing.JLabel jlblBoss;
    private javax.swing.JLabel jlblBottom;
    private javax.swing.JLabel jlblFront;
    private javax.swing.JLabel jlblTop;
    private javax.swing.JProgressBar jprogBarRage;
    private javax.swing.JLabel turnIndicator;
    // End of variables declaration//GEN-END:variables
}
