/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game_UI;
import Characters.*;
import javax.swing.ImageIcon;
import java.util.ArrayList;


/**
 *
 * @author Acer
 */
public class CharacterSelections extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CharacterSelections.class.getName());

    /**
     * Creates new form CharacterSelections
     */
    private ArrayList<GameCharacter> partyMembers = new ArrayList<>();
    private GameCharacter currentSelectedCharacter = null;
    private int parties = 0;
    public CharacterSelections() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabelImage = new javax.swing.JLabel();
        jlblname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnEthan = new javax.swing.JButton();
        jbtnDwight = new javax.swing.JButton();
        jbtnShawn = new javax.swing.JButton();
        jbtnPrincess = new javax.swing.JButton();
        jbtnOmar = new javax.swing.JButton();
        jtxtrole = new javax.swing.JTextField();
        jbtnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtparty = new javax.swing.JTextArea();
        jbtnstart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jlabelImage.setFocusable(false);

        jlblname.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jlblname.setForeground(new java.awt.Color(255, 0, 0));
        jlblname.setText("Ethan");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("CHARACTERS:");

        jbtnEthan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Ethan.png"))); // NOI18N
        jbtnEthan.addActionListener(this::jbtnEthanActionPerformed);

        jbtnDwight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Dwights.png"))); // NOI18N
        jbtnDwight.addActionListener(this::jbtnDwightActionPerformed);

        jbtnShawn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Shawn.png"))); // NOI18N
        jbtnShawn.addActionListener(this::jbtnShawnActionPerformed);

        jbtnPrincess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Camachos.png"))); // NOI18N
        jbtnPrincess.addActionListener(this::jbtnPrincessActionPerformed);

        jbtnOmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Omars.png"))); // NOI18N
        jbtnOmar.addActionListener(this::jbtnOmarActionPerformed);

        jtxtrole.setEditable(false);
        jtxtrole.setFont(new java.awt.Font("HelveticaNeueLTW06-97BlkCnObl", 0, 24)); // NOI18N
        jtxtrole.setFocusable(false);
        jtxtrole.addActionListener(this::jtxtroleActionPerformed);

        jbtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnAdd.setText("ADD TO PARTY");
        jbtnAdd.addActionListener(this::jbtnAddActionPerformed);

        jtxtDescription.setEditable(false);
        jtxtDescription.setColumns(20);
        jtxtDescription.setRows(5);
        jtxtDescription.setFocusable(false);
        jtxtDescription.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxtDescriptionInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtDescription);

        jtxtparty.setEditable(false);
        jtxtparty.setColumns(20);
        jtxtparty.setRows(5);
        jtxtparty.setFocusable(false);
        jScrollPane2.setViewportView(jtxtparty);

        jbtnstart.setText("START GAME");
        jbtnstart.addActionListener(this::jbtnstartActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtrole, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jlblname, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnDwight, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnEthan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnPrincess, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnShawn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnOmar)
                        .addGap(198, 198, 198)
                        .addComponent(jbtnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jtxtrole, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jlblname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbtnShawn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnEthan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnPrincess, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnDwight, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2))
                                .addGap(18, 18, 18)
                                .addComponent(jbtnOmar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122)))
                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void updateDisplay(GameCharacter character, String imagePath) {
        this.currentSelectedCharacter = character;
        String combined = String.join("\n", character.displayStats()) + "\n\n" 
                        + String.join("\n", character.getSkillname()) + "\n\n" 
                        + String.join("\n", character.getPassivename());
        
        jtxtrole.setText(character.getRole());
        jlblname.setText(character.getName());
        jtxtDescription.setText(combined);
        jlabelImage.setIcon(new ImageIcon(getClass().getResource(imagePath)));
    }
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
     if (currentSelectedCharacter == null) {
            jtxtparty.setText("Please select a character first!");
            return;
        }

        if (partyMembers.contains(currentSelectedCharacter)) {
            jtxtparty.setText("Character already in party!");
            return;
        }

        if (parties < 3) {
            partyMembers.add(currentSelectedCharacter);
            String position = (parties == 0) ? "[Front]" : (parties == 1) ? "[Top]" : "[Bottom]";
            jtxtparty.append(currentSelectedCharacter.getName() + " " + position + "\n");
            parties++;
        }
        
        if (parties == 3) {
            jtxtparty.append("(Party Full!)");
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jtxtroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtroleActionPerformed

    private void jbtnPrincessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrincessActionPerformed
        updateDisplay(new CharacterPrincess(), "/assets/Camachos.png");
    }//GEN-LAST:event_jbtnPrincessActionPerformed

    private void jbtnDwightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDwightActionPerformed
        // TODO add your handling code here:
        updateDisplay(new CharacterDwight(), "/assets/Dwights.png");

    }//GEN-LAST:event_jbtnDwightActionPerformed

    private void jbtnEthanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEthanActionPerformed
        updateDisplay(new CharacterEthan(), "/assets/Ethan.png");
    
    }//GEN-LAST:event_jbtnEthanActionPerformed

    private void jtxtDescriptionInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxtDescriptionInputMethodTextChanged
        
    }//GEN-LAST:event_jtxtDescriptionInputMethodTextChanged

    private void jbtnShawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShawnActionPerformed
        updateDisplay(new CharacterShawn(), "/assets/Shawn.png");
    }//GEN-LAST:event_jbtnShawnActionPerformed

    private void jbtnOmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOmarActionPerformed
        updateDisplay(new CharacterOmar(), "/assets/Omars.png");
    }//GEN-LAST:event_jbtnOmarActionPerformed

    private void jbtnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnstartActionPerformed
        if (parties < 3) {
            jtxtparty.setText("You must choose 3 characters to start!");
            return;
        }
        
        // Pass the party to the next screen
        BattleScreen nextJframe = new BattleScreen(partyMembers); 
        nextJframe.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jbtnstartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CharacterSelections().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDwight;
    private javax.swing.JButton jbtnEthan;
    private javax.swing.JButton jbtnOmar;
    private javax.swing.JButton jbtnPrincess;
    private javax.swing.JButton jbtnShawn;
    private javax.swing.JButton jbtnstart;
    private javax.swing.JLabel jlabelImage;
    private javax.swing.JLabel jlblname;
    private javax.swing.JTextArea jtxtDescription;
    private javax.swing.JTextArea jtxtparty;
    private javax.swing.JTextField jtxtrole;
    // End of variables declaration//GEN-END:variables
}
