/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game_UI;

import GameEngine.GameEngine;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        configureWindow();
    }

    private void configureWindow() {
        // Center the window and disable maximize/resize
        setLocationRelativeTo(null);
        setResizable(false);
        setExtendedState(javax.swing.JFrame.NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitle = new javax.swing.JLabel();
        j3btns = new javax.swing.JPanel();
        LoadGame = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitle.setBackground(new java.awt.Color(255, 255, 255));
        jTitle.setFont(new java.awt.Font("a Awal Ramadhan", 0, 48)); // NOI18N
        jTitle.setForeground(new java.awt.Color(255, 51, 51));
        jTitle.setText("STUDENTS VS FACULTY");
        jTitle.setFocusable(false);
        jTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 630, 80));

        j3btns.setLayout(new java.awt.BorderLayout());

        LoadGame.setBackground(new java.awt.Color(255, 204, 204));
        LoadGame.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        LoadGame.setText("Load Game");
        LoadGame.addActionListener(this::LoadGameActionPerformed);
        j3btns.add(LoadGame, java.awt.BorderLayout.LINE_END);

        Start.setBackground(new java.awt.Color(255, 204, 204));
        Start.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Start.setText("START GAME");
        Start.addActionListener(this::StartActionPerformed);
        j3btns.add(Start, java.awt.BorderLayout.CENTER);

        Quit.setBackground(new java.awt.Color(255, 204, 204));
        Quit.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Quit.setText("Quit\n");
        Quit.addActionListener(this::QuitActionPerformed);
        j3btns.add(Quit, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(j3btns, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, 80));

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MENU.png"))); // NOI18N
        jBackground.setText("jLabel3");
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        CharacterSelections nextJframe = new CharacterSelections();
        
        nextJframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StartActionPerformed

    private void LoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGameActionPerformed
        // Load a previously saved battle state.
        try {
            String startDir = System.getProperty("user.dir");
            File defaultSave = new File(startDir, "savegame.txt");
            if (!defaultSave.exists()) {
                JOptionPane.showMessageDialog(this, "Save file not found.", "Load Game", JOptionPane.ERROR_MESSAGE);
                return;
            }

            GameEngine loaded = GameEngine.loadStateFromFile(defaultSave.getAbsolutePath());
            if (loaded == null) {
                JOptionPane.showMessageDialog(this, "Failed to load save file.", "Load Game", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // If the save has no active boss, it's not a battle save
            if (loaded.getCurrentBoss() == null) {
                JOptionPane.showMessageDialog(this,
                    "This save does not contain an active battle.\nStarting character selection instead.",
                    "Load Game",
                    JOptionPane.INFORMATION_MESSAGE);
                CharacterSelections nextJframe = new CharacterSelections();
                nextJframe.setVisible(true);
                this.dispose();
                return;
            }

            BattleScreen battleScreen = new BattleScreen(loaded);
            battleScreen.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Load game failed", ex);
            JOptionPane.showMessageDialog(this,
                "Load failed: " + ex.getMessage(),
                "Load Game",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoadGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadGame;
    private javax.swing.JButton Quit;
    private javax.swing.JButton Start;
    private javax.swing.JPanel j3btns;
    private javax.swing.JLabel jBackground;
    private javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables
}
